/**
 * One-off seed: "Light – Reflection and Refraction" MCQ sets (Class X Physics).
 *
 * Writes 120 docs to the `mcqs` collection, chapterId "phys-x-c01":
 *   - setNumber 1-6  → English, 10 questions each (60 total)
 *   - setNumber 7-12 → Assamese translations of the same 60 questions
 *
 * Idempotent-ish: does NOT dedupe against pre-existing docs for this chapter —
 * intended to run exactly once. If re-run, it will create duplicates.
 *
 * AUTH: set GOOGLE_APPLICATION_CREDENTIALS to the service-account JSON path:
 *   $env:GOOGLE_APPLICATION_CREDENTIALS = "C:\path\to\key.json"
 *   npx tsx scripts/src/seed-light-mcqs.ts
 */

import { initializeApp, cert, getApps, applicationDefault } from "firebase-admin/app";
import { getFirestore } from "firebase-admin/firestore";

const PROJECT_ID = "true-concept-353c9";
const CHAPTER_ID = "phys-x-c01";

if (getApps().length === 0) {
  const credential = process.env.TRUE_CONCEPT_SERVICE_KEY
    ? cert(JSON.parse(Buffer.from(process.env.TRUE_CONCEPT_SERVICE_KEY, "base64").toString("utf8")))
    : applicationDefault();
  initializeApp({ credential, projectId: PROJECT_ID });
  console.log(`→ Connecting to LIVE Firestore project: ${PROJECT_ID}`);
}

const db = getFirestore();

interface McqInput {
  question: string;
  options: [string, string, string, string];
  correctIndex: number;
  explanation: string;
  setNumber: number;
  order: number;
}

const AR_OPTIONS_EN: [string, string, string, string] = [
  "A is true, R is true; R is a correct explanation for A.",
  "A is true, R is true; R is not a correct explanation for A.",
  "A is true; R is False.",
  "A is false; R is true.",
];

const AR_OPTIONS_AS: [string, string, string, string] = [
  "A সঁচা, R সঁচা; R এ A ৰ সঠিক ব্যাখ্যা দিয়ে।",
  "A সঁচা, R সঁচা; R এ A ৰ সঠিক ব্যাখ্যা নিদিয়ে।",
  "A সঁচা; R ভুল।",
  "A ভুল; R সঁচা।",
];

// ─── English: 60 questions, sets 1-6 ───────────────────────────────────────
const englishQuestions: Omit<McqInput, "setNumber" | "order">[] = [
  { question: "A concave mirror produces three times magnified real image of an object placed at 10 cm in front of it. The image is located at ......", options: ["30 cm", "40 cm", "10 cm", "90 cm"], correctIndex: 0, explanation: "For a real image, magnification M = −v/u. Given u = −10 cm and M = −3 (real image is inverted): −3 = −v/−10 ⟹ v = −30 cm. So the image forms 30 cm in front of the mirror." },
  { question: "The radius of curvature of a concave mirror is 12 cm. Then, the focal length will be", options: ["12 cm", "6 cm", "-24 cm", "-6 cm"], correctIndex: 3, explanation: "Focal length of a concave mirror is negative: f = −R/2 = −12/2 = −6 cm." },
  { question: "The image of an object is real, inverted and smaller in size, if it is placed before a mirror which is", options: ["convex", "concave", "plane", "None of the above"], correctIndex: 1, explanation: "When an object is placed between the centre of curvature and focus of a concave mirror, a real, inverted and diminished image is formed." },
  { question: "What will be the position and nature of the image of an object formed by a convex mirror placed between infinity and pole (P) of the mirror?", options: ["In between pole (P) and focus (f) behind mirror, virtual and erect", "In between pole (P) and focus (f) behind mirror, virtual and inverted", "In front of mirror, real and erect", "In front of mirror, virtual and erect"], correctIndex: 0, explanation: "For a convex mirror, the image of any real object (anywhere between infinity and the pole) always forms between the pole and focus, behind the mirror, and is virtual and erect." },
  { question: "Which of the following can make a parallel beam of light when light from a point source is incident on it?", options: ["Concave mirror as well as convex lens", "Convex mirror as well as concave lens", "Two plane mirrors placed at 90° to each other", "Concave mirror as well as concave lens"], correctIndex: 0, explanation: "A ray passing through the principal focus of a concave mirror or a convex lens emerges parallel to the principal axis after reflection/refraction. So placing a point source at the focus of a concave mirror or a convex lens produces a parallel beam." },
  { question: "A doctor has prescribed a corrective lens of power +1.5D. The nature of lens is", options: ["diverging", "converging", "half diverging", "None of these"], correctIndex: 1, explanation: "Focal length f = 1/P = 1/1.5 m ≈ 66.7 cm, which is positive — so the lens is a converging (convex) lens." },
  { question: "The image of an object placed in front of a lens is formed at a distance three times to that of the object, the magnification of the image is", options: ["1", "2", "3", "4"], correctIndex: 2, explanation: "Magnification m = v/u = 3u/u = 3." },
  { question: "Whose sight area is the highest?", options: ["Plane mirror", "Convex mirror", "Concave mirror", "Concave lens"], correctIndex: 1, explanation: "A convex mirror has the highest sight area (field of view) because it forms diminished images of objects at different positions, fitting a wider scene into the same mirror size." },
  { question: "Nature of image formed by a concave lens is always real and erect.", options: ["True", "False", "Can't say", "Partially true/false"], correctIndex: 3, explanation: "Partially true — the image formed by a concave lens is always virtual and erect, never real. So 'erect' is correct but 'real' is wrong, making the statement partially true." },
  { question: "A light ray is incident on a rectangular glass slab at an angle of 60°. The angle between the ray coming out of the slab and the normal to the face of rectangular slab from which it comes out is", options: ["30°", "60°", "90°", "0°"], correctIndex: 1, explanation: "For a rectangular slab, the angle of incidence equals the angle of emergence — both 60° — since the emergent ray is parallel to the incident ray." },
  { question: "For which of the following image of an object placed at infinity will be highly diminished and point sized?", options: ["Convex mirror only", "Concave mirror only", "Convex lens only", "Concave mirror, convex mirror, concave lens and convex lens"], correctIndex: 3, explanation: "Parallel rays from infinity converge to (or appear to diverge from) the principal focus after reflection/refraction by all four — concave mirror, convex mirror, concave lens and convex lens — giving a highly diminished, point-sized image in each case." },
  { question: "You are given water, mustard oil, glycerine and kerosene. In which of these media, a ray of light incident obliquely at same angle would bend the most?", options: ["Kerosene", "Water", "Mustard oil", "Glycerine"], correctIndex: 3, explanation: "Refractive indices: kerosene 1.44, water 1.33, mustard oil 1.46, glycerine 1.74. Glycerine has the highest refractive index, so it bends light the most." },
  { question: "For a convex mirror, parallel rays of light appear to diverge from a point called ···········", options: ["radius of curvature", "pole", "aperture", "principal focus"], correctIndex: 3, explanation: "By definition, the principal focus of a convex mirror is the point from which parallel rays appear to diverge after reflection." },
  { question: "As the refractive indices of water, glass and sulphuric acid are 1.33, 1.53 and 1.43 respectively, hence light travels slowest in sulphuric acid.", options: ["True", "False", "Can't say", "Partially true/false"], correctIndex: 1, explanation: "False — speed v ∝ 1/refractive index, so light travels slowest in the medium with the highest refractive index, which is glass (1.53), not sulphuric acid (1.43)." },
  { question: "The focal length of a spherical mirror is 10 cm. Hence, its radius of curvature will be 5 cm.", options: ["True", "False", "Can't say", "Partially true/false"], correctIndex: 1, explanation: "False — R = 2f = 2 × 10 = 20 cm, not 5 cm." },
  { question: "Speed of light in vacuum is 3×10⁸ m/s. Then, speed of light in glass (refractive index 1.5) will be", options: ["4.5×10⁸ m/s", "2.0×10⁶ m/s", "3.0×10⁶ m/s", "2.0×10⁸ m/s"], correctIndex: 3, explanation: "v = c/n = (3×10⁸)/1.5 = 2.0×10⁸ m/s." },
  { question: "A ray of light travelling from air enters a liquid at an angle of 45° with the normal. If the corresponding angle of refraction is 30°, then the refractive index of the liquid with respect to air is", options: ["1.44", "1.41", "1.21", "1.45"], correctIndex: 1, explanation: "n = sin i / sin r = sin45°/sin30° ≈ 0.707/0.5 ≈ 1.41." },
  { question: "When an object is kept within the focus of a concave mirror, an enlarged image is formed behind the mirror. This image is", options: ["real", "inverted", "virtual and inverted", "virtual and erect"], correctIndex: 3, explanation: "Object between the pole and focus of a concave mirror forms a virtual, erect, magnified image behind the mirror." },
  { question: "To make an image real, inverted and larger than the object with a convex lens of focal length f, the object should be placed", options: ["on the focus of lens", "on the distance 2f of lens", "between f and 2f of lens", "between 2f and infinity"], correctIndex: 2, explanation: "When the object is placed between f and 2f of a convex lens, the image formed is real, inverted and magnified (larger than the object), beyond 2f on the other side." },
  { question: "The relation between focal length f and radius of curvature R for a spherical mirror is", options: ["f = 2R", "f = R/2", "f = R/4", "f = 2/R"], correctIndex: 1, explanation: "For any spherical mirror, f = R/2." },
  { question: "In which of the following media, velocity of the light will be maximum?", options: ["Air", "Water", "Glass", "Vacuum"], correctIndex: 3, explanation: "Light travels fastest in vacuum, at 3×10⁸ m/s — its maximum possible speed." },
  { question: "The radius of curvature of a concave lens is 20 cm. Its focal length will be", options: ["-20 cm", "-10 cm", "40 cm", "10 cm"], correctIndex: 1, explanation: "f = R/2 = 20/2 = 10 cm in magnitude; since it's a concave (diverging) lens, f = −10 cm." },
  { question: "Magnification produced by a rear view mirror fitted in vehicles", options: ["is less than one", "is more than one", "is equal to one", "(a) or (b) depending upon the position of the object"], correctIndex: 0, explanation: "A rear-view mirror is a convex mirror, which always forms a virtual, erect, diminished image — so its magnification is always less than one (m < 1)." },
  { question: "Consider the following propoerties of virtual images\nA. cannot be projected on the screen   B. are formed by both concave and convex lens\nC. are always erect   D. are always inverted\nThe correct properties are", options: ["(A) and (D)", "(A) and (B)", "(A), (B) and (C)", "(A), (B) and (D)"], correctIndex: 2, explanation: "Virtual images are always erect, cannot be projected on a screen, and are formed by both concave and convex lenses. So A, B and C are correct; D is wrong since virtual images are never inverted." },
  { question: "Rays from sun converge at a point 15 cm in front of a concave mirror. Where should an object be placed so that size of its image is equal to the size of the object?", options: ["15 cm in front of the mirror", "30 cm in front of the mirror", "between 15 cm and 30 cm in front of the mirror", "more than 30 cm in front of the mirror"], correctIndex: 1, explanation: "Parallel rays from the sun converge at the focus, so f = 15 cm. A same-size, real, inverted image forms only when the object is at the centre of curvature, i.e. at 2f = 30 cm." },
  { question: "Which of the following is not correct?", options: ["Light is an electromagnetic wave", "Light travels in a straight line", "Light is a transverse wave", "Light is a longitudinal wave"], correctIndex: 3, explanation: "Light is an electromagnetic, transverse wave that travels in a straight line — it is NOT a longitudinal wave, so statement (d) is incorrect." },
  { question: "Magnification produced by ·········· lens is always less than 1.", options: ["concave", "convex", "any", "cylindrical"], correctIndex: 0, explanation: "A concave lens always forms a diminished (smaller), virtual, erect image for any object position, so its magnification is always less than 1." },
  { question: "A real image is formed by the light rays after reflection or refraction when they\nI. actually meet or intersect with each other.\nII. actually converge at a point.\nIII. appear to meet when they are produced in the backward direction.\nIV. appear to diverge from a point.\nWhich of the above statements are correct?", options: ["(I) and (IV)", "(II) and (IV)", "(I) and (II)", "(II) and (III)"], correctIndex: 2, explanation: "A real image forms only when light rays actually meet/intersect or actually converge at a point after reflection or refraction — statements I and II describe the same condition for a real image." },
  { question: "A concave lens of focal length f forms an image which is n times the size of object. The distance of object from the lens is", options: ["(1−n)f", "(1+n)f", "((1+n)/n)f", "((1−n)/n)f"], correctIndex: 3, explanation: "Using v = nu and the lens formula 1/v − 1/u = 1/f, solving gives u = ((1−n)/n) f." },
  { question: "A girl is standing in front of a magic mirror. She finds the image of her head bigger, the middle portion of her body of the same size and that of the legs smaller. The following is the order of combinations for the magic mirror from the top.", options: ["Plane, convex and concave", "Convex, concave and plane", "Concave, plane and convex", "Convex, plane and concave"], correctIndex: 2, explanation: "A concave mirror (of large focal length) magnifies the head, a plane mirror keeps the middle portion the same size, and a convex mirror diminishes the legs — so from top to bottom: concave, plane, convex." },
  { question: "Image formed by a mirror is always straight (erect) whatever will be the distance, then mirror is", options: ["only plane", "only concave", "only convex", "either plane or convex"], correctIndex: 3, explanation: "Plane and convex mirrors always form an erect image for any object distance." },
  { question: "Focal length of a plane mirror is", options: ["zero", "infinite", "25 cm", "-25 cm"], correctIndex: 1, explanation: "A plane mirror can be thought of as a spherical mirror of infinite radius of curvature, so its focal length is infinite." },
  { question: "The laws of reflection hold good for", options: ["plane mirror only", "concave mirror only", "convex mirror only", "all mirrors irrespective of their shape"], correctIndex: 3, explanation: "The laws of reflection hold for light reflected from any smooth surface, regardless of the mirror's shape." },
  { question: "Light ray is incident normally on the boundary surface of two media, then angle of refraction will be", options: ["Zero", "45°", "60°", "80°"], correctIndex: 0, explanation: "When light is incident normally (along the normal), both the angle of incidence and angle of refraction are zero — the ray passes straight through without bending." },
  { question: "A spherical mirror and a thin spherical lens each have a focal length of −15 cm. The mirror and lens are likely to be", options: ["both concave", "both convex", "mirror is concave and lens is convex", "mirror is convex and lens is concave"], correctIndex: 0, explanation: "A negative focal length is taken for a concave mirror as well as a concave (diverging) lens — so both must be concave." },
  { question: "A light ray travels from medium A into medium B and bends towards the normal as it enters medium B. The refractive index of medium B relative to medium A will be", options: ["greater than unity", "less than unity", "equal to unity", "zero"], correctIndex: 0, explanation: "Since the ray bends towards the normal on entering medium B, medium B is optically denser and has a greater refractive index, with a lesser speed of light, than medium A — so the refractive index of B relative to A is greater than unity." },
  { question: "An object is placed 20 cm from the concave mirror of focal length 10 cm, then image is formed ……", options: ["behind the mirror", "between the mirror and focus", "at focus", "centre of curvature of mirror"], correctIndex: 3, explanation: "Using the mirror formula with f = −10 cm, u = −20 cm: 1/v = 1/f − 1/u = −1/10 + 1/20 = −1/20, so v = −20 cm — the image forms at the centre of curvature of the mirror." },
  { question: "Match Column I (Terms or laws) with Column II (Formula or relation):\nA. Lens formula  B. Snell's law  C. Refractive index  D. Power of lens\n(i) ∠i = ∠r  (ii) 1/v − 1/u = 1/f  (iii) c/v  (iv) 1/f (in metre)", options: ["(i)(iii)(iv)(ii)", "(ii)(iv)(i)(iii)", "(ii)(i)(iii)(iv)", "(iii)(i)(iv)(ii)"], correctIndex: 2, explanation: "A→(ii) lens formula 1/v−1/u=1/f; B→(i) Snell's law relation; C→(iii) refractive index = c/v; D→(iv) power of lens = 1/f (in metre). So the code is (ii)(i)(iii)(iv)." },
  { question: "Nature of a mirror having a focal length +10 cm is converging in nature.", options: ["True", "False", "Can't say", "Partially true/false"], correctIndex: 1, explanation: "False — a positive focal length belongs to a convex (diverging) mirror; converging (concave) mirrors have negative focal length." },
  { question: "Two parallel beams of light enter a closed box through two separate holes and emerge from two other holes on the opposite side, still parallel to the original beams (only laterally shifted). Which of the following could be inside the box?", options: ["A rectangular glass slab", "A convex lens", "A concave lens", "A prism"], correctIndex: 0, explanation: "A rectangular glass slab bends a ray by equal and opposite amounts at its two parallel faces, so the emergent ray is parallel to (only laterally shifted from) the incident ray — exactly matching the box's behaviour." },
  { question: "An object is placed at a distance of 10 cm in front of a plane mirror, then the distance of image from mirror will be", options: ["5 cm", "10 cm", "20 cm", "0"], correctIndex: 1, explanation: "In a plane mirror, the image distance behind the mirror always equals the object distance in front of it — so 10 cm." },
  { question: "No refraction of light occurs if the ray of light hits the boundary of interface of medium at an angle of 90°.", options: ["True", "False", "Can't say", "Partially true/false"], correctIndex: 0, explanation: "True — at normal incidence (angle of incidence = 0°, i.e. the ray travels along the normal which is at 90° to the surface), both angle of incidence and refraction are 0°, so the ray passes straight through with no bending." },
  { question: "Match Column I (Magnification, m) with Column II (Nature of image):\nA. m = 1  B. m < 1  C. m > 0  D. m < 0\n(i) Inverted image  (ii) Diminished image  (iii) Erect image  (iv) Size of image = Size of object", options: ["(iv)(ii)(iii)(i)", "(ii)(iv)(ii)(iii)", "(iv)(iii)(ii)(i)", "(i)(ii)(iii)(iv)"], correctIndex: 0, explanation: "A→(iv): m=1 means image size equals object size. B→(ii): m<1 means diminished image. C→(iii): m>0 means erect image. D→(i): m<0 means inverted image. So the code is (iv)(ii)(iii)(i)." },
  { question: "A 10 mm long awl pin is placed vertically in front of a concave mirror. A 5 mm long image of the awl pin is formed at 30 cm in front of the mirror. The focal length of this mirror is", options: ["-30 cm", "-20 cm", "-40 cm", "-60 cm"], correctIndex: 1, explanation: "h = 1 cm, h' = −0.5 cm (real image), v = −30 cm. m = −v/u = h'/h ⟹ −(−30)/u = −0.5 ⟹ u = −60 cm. Using mirror formula: 1/f = 1/v + 1/u = 1/(−30) + 1/(−60) = −3/60 ⟹ f = −20 cm." },
  { question: "Where an object should be placed in front of the concave mirror, so that its image be erect and larger in size?", options: ["At the centre of curvature (C) of the mirror", "At the focus point (f) of the mirror", "In between the centre of curvature (C) and the focus point (f) of the mirror", "In between the pole (P) and the focus point (f) of the mirror"], correctIndex: 3, explanation: "Only when the object is placed between the pole (P) and the focus (f) of a concave mirror is the image virtual, erect and magnified (larger in size)." },
  { question: "A convex mirror of focal length f produces an image 1/n th of the size of the object. The distance of the object from the mirror is ……", options: ["((n+1)/n)f", "(n+1)f", "(n−1)f", "((n−1)/n)f"], correctIndex: 1, explanation: "From m = 1/n = −v/(−u) ⟹ v = u/n; using the mirror formula 1/v + 1/u = 1/f gives n/u + 1/u = 1/f, so u = (n+1)f." },
  { question: "To determine the focal length of a concave mirror by forming image of a distant object, the screen should be placed", options: ["in any direction", "inclined at angle of 45°", "at right angle to the plane of mirror", "parallel to the plane of mirror"], correctIndex: 3, explanation: "The image formed by a concave mirror is always perpendicular to the principal axis, so the screen must be placed parallel to the plane of the mirror to capture it clearly." },
  { question: "If a ray of light passes from denser to rarer medium, the angle of refraction will be lesser than the angle of incidence.", options: ["True", "False", "Can't say", "Partially true/false"], correctIndex: 1, explanation: "False — going from a denser to a rarer medium, the ray bends away from the normal, so the angle of refraction is actually GREATER than the angle of incidence." },
  { question: "Assertion (A): Keeping a point object fixed, if a plane mirror is moved, the image will also move.\nReason (R): In case of a plane mirror, distance of object and its image is equal from any point.", options: AR_OPTIONS_EN, correctIndex: 0, explanation: "The image in a plane mirror is always as far behind the mirror as the object is in front. If the mirror moves while the object stays fixed, this equal-distance relationship forces the image to move too — so R correctly explains A." },
  { question: "Assertion (A): Property of converging lens does not remain same in all media.\nReason (R): Property of lens — whether the ray is diverging or converging — is independent of the surrounding medium.", options: AR_OPTIONS_EN, correctIndex: 2, explanation: "A lens's behaviour does depend on the refractive index of the surrounding medium. So A is true (converging property changes with medium) but R is false (it wrongly claims independence from the medium)." },
  { question: "Assertion (A): When a concave mirror is held under water, its focal length will increase.\nReason (R): The focal length of a concave mirror is independent of the medium in which it is placed.", options: AR_OPTIONS_EN, correctIndex: 3, explanation: "Focal length is a property of the mirror's geometry and is independent of the surrounding medium — so when held under water, its focal length stays the same, it does NOT increase. A is false, R is true." },
  { question: "Assertion (A): A convex lens is made of two different materials. A point object is placed on the principal axis. The number of images formed by the lens will be two.\nReason (R): The image formed by convex lens is always virtual.", options: AR_OPTIONS_EN, correctIndex: 2, explanation: "Since the lens is made of two materials, it has two refractive indices and two focal lengths, so two images form — A is true. But the image formed by a convex lens is usually real (only virtual when the object is between the focus and optical centre), so R is false." },
  { question: "Assertion (A): Although the surfaces of a goggles, lenses are curved, it does not have any power.\nReason (R): In case of goggles, both the curved surfaces have equal radii of curvature.", options: AR_OPTIONS_EN, correctIndex: 0, explanation: "Because both curved surfaces of goggles have equal radii of curvature, the focal length becomes infinite, so power P = 1/f = 0. A is true, R is true, and R correctly explains A." },
  { question: "Read the following and answer: light is a form of energy which induces sensation of vision to our eyes; reflection is the bouncing back of light rays on hitting a smooth surface. The mirror outside the driver's side of a vehicle is usually a spherical mirror, printed with the warning 'vehicles in this mirror are closer than they appear.' Which type of mirror is used outside the driver's side of a vehicle?", options: ["Plane mirror", "Concave mirror", "Convex mirror", "Magic mirror"], correctIndex: 2, explanation: "Convex mirrors are used as side mirrors in vehicles because they always give an erect image and have a wider field of view, helping the driver see more of the road behind." },
  { question: "(Same passage as above) No matter how far you stand from a mirror, your image appears erect. The mirror can be", options: ["Plane", "Concave", "convex", "Either plane or convex"], correctIndex: 3, explanation: "Both plane and convex mirrors always form an erect image for an object at any distance, so the mirror can be either plane or convex." },
  { question: "(Same passage as above) If an object is placed at 10 cm from a convex mirror of radius of curvature 60 cm, then find the position of image.", options: ["4 cm", "7.5 cm", "10 cm", "12.5 cm"], correctIndex: 1, explanation: "f = R/2 = 30 cm (positive, convex mirror). u = −10 cm. By mirror formula 1/v = 1/f − 1/u = 1/30 − (−1/10) = 1/30 + 1/10 = 4/30 ⟹ v = 7.5 cm." },
  { question: "(Same passage as above) The focal length of mirror is 12 cm. The radius of curvature is", options: ["12 cm", "24 cm", "20 cm", "36 cm"], correctIndex: 1, explanation: "Radius of curvature R = 2f = 2 × 12 = 24 cm." },
  { question: "Read the following and answer: the refractive index of a medium with respect to vacuum is called its absolute refractive index, μ = sin i / sin r. How is absolute refractive index related to speed of light?", options: ["μ = c/v_m", "μ = c·v_m", "μ_c = V_m", "vμ = c"], correctIndex: 0, explanation: "Absolute refractive index μ = (speed of light in vacuum, c) / (speed of light in that medium, v_m), i.e. μ = c/v_m." },
  { question: "(Same passage as above) Absolute refractive indices of media A, B, C and D are 1.54, 1.33, 2.42 and 1.65 respectively. In which of these media does light travel fastest?", options: ["A", "B", "C", "D"], correctIndex: 1, explanation: "B has the lowest refractive index (1.33), meaning it is the least optically dense, so light travels fastest in medium B." },
  { question: "(Same passage as above) The speed of light in air is 3×10⁸ ms⁻¹ and that in medium A is 2.5×10⁸ ms⁻¹. The refractive index of A will be", options: ["1.2", "0.5", "4.5", "1.5"], correctIndex: 0, explanation: "Refractive index of A = speed of light in air / speed of light in medium A = (3×10⁸)/(2.5×10⁸) = 1.2." },
];

// ─── Assamese: same 60 questions, sets 7-12 ────────────────────────────────
const assameseQuestions: Omit<McqInput, "setNumber" | "order">[] = [
  { question: "এটা অবতল দৰ্পণে ইয়াৰ সমুখত 10 cm দূৰত্বত থোৱা বস্তুৰ তিনিগুণ বিবৰ্ধিত বাস্তৱ প্রতিবিম্ব সৃষ্টি কৰে। প্রতিবিম্বটো ............ ত গঠন হয়।", options: ["30 cm", "40 cm", "10 cm", "90 cm"], correctIndex: 0, explanation: "বাস্তৱ প্রতিবিম্বৰ বাবে, বিবৰ্ধন M = −v/u। u = −10 cm আৰু M = −3 (বাস্তৱ প্রতিবিম্ব উলোটা): −3 = −v/−10 ⟹ v = −30 cm। সেয়েহে প্রতিবিম্বটো দৰ্পণৰ সমুখত 30 cm দূৰত্বত গঠন হয়।" },
  { question: "এটা অবতল দৰ্পণৰ বক্রতার ব্যাসাৰ্ধ 12 cm। তাৰ ফোকাস দূরত্ব হ'ব—", options: ["12 cm", "6 cm", "-24 cm", "-6 cm"], correctIndex: 3, explanation: "অবতল দৰ্পণৰ ফোকাস দূরত্ব ঋণাত্মক হয়: f = −R/2 = −12/2 = −6 cm।" },
  { question: "কোনটো দৰ্পণৰ সমুখত বস্তু থ'লে বাস্তৱ, উলোটা আৰু সৰু আকাৰৰ প্রতিবিম্ব গঠন হয়?", options: ["উত্তল", "অবতল", "সমতল", "ওপৰৰ কোনোটো নহয়"], correctIndex: 1, explanation: "অবতল দৰ্পণৰ বক্রতার কেন্দ্র আৰু ফোকাসৰ মাঝত বস্তু থ'লে বাস্তৱ, উলোটা আৰু সৰু (সংকুচিত) প্রতিবিম্ব গঠন হয়।" },
  { question: "অনন্ত আৰু ধ্রুৱ (P) ৰ মাঝত থোৱা বস্তুৰ বাবে উত্তল দৰ্পণে গঠন কৰা প্রতিবিম্বৰ স্থান আৰু প্রকৃতি কি হ'ব?", options: ["ধ্রুৱ (P) আৰু ফোকাস (f) ৰ মাঝত দৰ্পণৰ পিছফালে, কাল্পনিক আৰু সোজা", "ধ্রুৱ (P) আৰু ফোকাস (f) ৰ মাঝত দৰ্পণৰ পিছফালে, কাল্পনিক আৰু উলোটা", "দৰ্পণৰ সমুখফালে, বাস্তৱ আৰু সোজা", "দৰ্পণৰ সমুখফালে, কাল্পনিক আৰু সোজা"], correctIndex: 0, explanation: "উত্তল দৰ্পণৰ বাবে, যিকোনো বাস্তৱ বস্তুৰ (অনন্ত আৰু ধ্রুৱৰ মাঝত য'তেই থাকক) প্রতিবিম্ব সদায় ধ্রুৱ আৰু ফোকাসৰ মাঝত, দৰ্পণৰ পিছফালে গঠন হয়, আৰু সেইটো কাল্পনিক আৰু সোজা হয়।" },
  { question: "বিন্দু উৎসৰপৰা আহি যিকোনো বস্তুৰ ওপৰত পৰিলে, কোনটোৱে সমান্তরাল ৰশ্মিপুঞ্জ সৃষ্টি কৰিব পাৰে?", options: ["অবতল দৰ্পণ আৰু উত্তল লেন্স দুয়োটাই", "উত্তল দৰ্পণ আৰু অবতল লেন্স দুয়োটাই", "90° কোণত থোৱা দুটা সমতল দৰ্পণ", "অবতল দৰ্পণ আৰু অবতল লেন্স দুয়োটাই"], correctIndex: 0, explanation: "অবতল দৰ্পণ বা উত্তল লেন্সৰ মূখ্য ফোকাসৰ মাজেৰে যোৱা ৰশ্মি প্রতিফলন/প্রতিসরণৰ পিছত মূখ্য অক্ষৰ সমান্তরালে নিৰ্গত হয়। সেয়েহে বিন্দু উৎসটো অবতল দৰ্পণ বা উত্তল লেন্সৰ ফোকাসত থ'লে সমান্তরাল ৰশ্মিপুঞ্জ পাব।" },
  { question: "এজন চিকিৎসকে +1.5D ক্ষমতাৰ সংশোধনী লেন্স নিৰ্দেশ দিছে। লেন্সটোৰ প্রকৃতি হ'ল—", options: ["অপসারী (diverging)", "অভিসারী (converging)", "অর্ধ অপসারী", "ওপৰৰ কোনোটো নহয়"], correctIndex: 1, explanation: "ফোকাস দূরত্ব f = 1/P = 1/1.5 m ≈ 66.7 cm, যিটো ধনাত্মক — সেয়েহে লেন্সটো অভিসারী (উত্তল) লেন্স।" },
  { question: "এটা লেন্সৰ সমুখত থোৱা বস্তুৰ প্রতিবিম্ব বস্তুটোৰ দূরত্বৰ তিনিগুণ দূরত্বত গঠন হয়। প্রতিবিম্বৰ বিবৰ্ধন হ'ল—", options: ["1", "2", "3", "4"], correctIndex: 2, explanation: "বিবৰ্ধন m = v/u = 3u/u = 3।" },
  { question: "কোনটোৰ দৃষ্টি ক্ষেত্ৰ (sight area) আটাইতকৈ বেছি?", options: ["সমতল দৰ্পণ", "উত্তল দৰ্পণ", "অবতল দৰ্পণ", "অবতল লেন্স"], correctIndex: 1, explanation: "উত্তল দৰ্পণৰ দৃষ্টি ক্ষেত্ৰ আটাইতকৈ বেছি, কাৰণ ই বিভিন্ন স্থানত থোৱা বস্তুৰ সংকুচিত প্রতিবিম্ব সৃষ্টি কৰি অধিক দৃশ্য দৰ্পণৰ একেটা আকাৰতেই দেখুৱায়।" },
  { question: "অবতল লেন্সে গঠন কৰা প্রতিবিম্ব সদায় বাস্তৱ আৰু সোজা হয়।", options: ["সঁচা", "ভুল", "কব নোৱাৰি", "আংশিক সঁচা/ভুল"], correctIndex: 3, explanation: "আংশিক সঁচা — অবতল লেন্সে গঠন কৰা প্রতিবিম্ব সদায় কাল্পনিক আৰু সোজা হয়, কেতিয়াও বাস্তৱ নহয়। সেয়েহে 'সোজা' সঁচা কিন্তু 'বাস্তৱ' ভুল, গতিকে কথাটো আংশিক সঁচা।" },
  { question: "এটা আয়তাকার কাঁচ স্লাবৰ ওপৰত 60° কোণত আপতিত হোৱা ৰশ্মি স্লাবৰ যি পৃষ্ঠৰপরা নিৰ্গত হয়, তাৰ স্বাভাৱিকৰ সৈতে নিৰ্গত ৰশ্মি আৰু সেই স্বাভাৱিকৰ মাজৰ কোণ হ'ল—", options: ["30°", "60°", "90°", "0°"], correctIndex: 1, explanation: "আয়তাকার স্লাবৰ বাবে আপতন কোণ আৰু নিৰ্গমন কোণ সমান হয় — দুয়োটাই 60°, কাৰণ নিৰ্গত ৰশ্মি আপতিত ৰশ্মিৰ সমান্তরাল হয়।" },
  { question: "অনন্ত দূরত্বত থোৱা বস্তুৰ প্রতিবিম্ব অতি সংকুচিত আৰু বিন্দু আকৃতিৰ হ'ব কোনটোৰ বাবে?", options: ["কেৱল উত্তল দৰ্পণ", "কেৱল অবতল দৰ্পণ", "কেৱল উত্তল লেন্স", "অবতল দৰ্পণ, উত্তল দৰ্পণ, অবতল লেন্স আৰু উত্তল লেন্স সকলো"], correctIndex: 3, explanation: "অনন্তৰপরা আহি সমান্তরাল ৰশ্মি প্রতিফলন/প্রতিসরণৰ পিছত এই সকলো — অবতল দৰ্পণ, উত্তল দৰ্পণ, অবতল লেন্স আৰু উত্তল লেন্স — ৰে মূখ্য ফোকাসত অভিসারিত হয় বা অভিসারিত হোৱা যেন দেখা যায়, ফলত প্রতিটোৰেই প্রতিবিম্ব অতি সংকুচিত আৰু বিন্দু আকৃতিৰ হয়।" },
  { question: "পানী, সৰিয়হ তেল, গ্লিচাৰিন আৰু কেৰাচিনৰ মাজত একে কোণত তিৰ্যকভাৱে আপতিত ৰশ্মি কোনটোত আটাইতকৈ বেছি বঁকা হ'ব?", options: ["কেৰাচিন", "পানী", "সৰিয়হ তেল", "গ্লিচাৰিন"], correctIndex: 3, explanation: "প্রতিসরাংক: কেৰাচিন 1.44, পানী 1.33, সৰিয়হ তেল 1.46, গ্লিচাৰিন 1.74। গ্লিচাৰিনৰ প্রতিসরাংক আটাইতকৈ বেছি, সেয়েহে ই আলোক আটাইতকৈ বেছি বঁকায়।" },
  { question: "উত্তল দৰ্পণৰ বাবে, সমান্তরাল ৰশ্মি যি বিন্দুৰপরা অপসারিত হোৱা যেন লাগে, তাকে কি বোলে?", options: ["বক্রতার ব্যাসাৰ্ধ", "ধ্রুৱ", "ছিদ্র (aperture)", "মূখ্য ফোকাস"], correctIndex: 3, explanation: "সংজ্ঞা অনুসৰি, উত্তল দৰ্পণৰ মূখ্য ফোকাস হ'ল সেই বিন্দু যাৰপরা প্রতিফলনৰ পিছত সমান্তরাল ৰশ্মি অপসারিত হোৱা যেন লাগে।" },
  { question: "পানী, কাঁচ আৰু সালফিউৰিক এসিডৰ প্রতিসরাংক ক্রমে 1.33, 1.53 আৰু 1.43, সেয়েহে আলোক সালফিউৰিক এসিডত আটাইতকৈ লেহেমে যাত্রা কৰে।", options: ["সঁচা", "ভুল", "কব নোৱাৰি", "আংশিক সঁচা/ভুল"], correctIndex: 1, explanation: "ভুল — বেগ v ∝ 1/প্রতিসরাংক, সেয়েহে আলোক আটাইতকৈ বেছি প্রতিসরাংক থোৱা মাধ্যমত আটাইতকৈ লেহেমে যাত্রা কৰে, যিটো কাঁচ (1.53), সালফিউৰিক এসিড (1.43) নহয়।" },
  { question: "এটা গোলকীয় দৰ্পণৰ ফোকাস দূরত্ব 10 cm। সেয়েহে তাৰ বক্রতার ব্যাসাৰ্ধ 5 cm হ'ব।", options: ["সঁচা", "ভুল", "কব নোৱাৰি", "আংশিক সঁচা/ভুল"], correctIndex: 1, explanation: "ভুল — R = 2f = 2 × 10 = 20 cm, 5 cm নহয়।" },
  { question: "শূন্যস্থানত আলোকৰ বেগ 3×10⁸ m/s। তেন্তে কাঁচত (প্রতিসরাংক 1.5) আলোকৰ বেগ হ'ব—", options: ["4.5×10⁸ m/s", "2.0×10⁶ m/s", "3.0×10⁶ m/s", "2.0×10⁸ m/s"], correctIndex: 3, explanation: "v = c/n = (3×10⁸)/1.5 = 2.0×10⁸ m/s।" },
  { question: "বাতাসৰপরা আহি এটা ৰশ্মি লিকুইডত 45° কোণত আপতিত হয়। প্রতিসরণ কোণ 30° হ'লে, বাতাসৰ প্রতি লিকুইডৰ প্রতিসরাংক হ'ব—", options: ["1.44", "1.41", "1.21", "1.45"], correctIndex: 1, explanation: "n = sin i / sin r = sin45°/sin30° ≈ 0.707/0.5 ≈ 1.41।" },
  { question: "অবতল দৰ্পণৰ ফোকাসৰ ভিতৰত বস্তু থ'লে দৰ্পণৰ পিছফালে বিবৰ্ধিত প্রতিবিম্ব গঠন হয়। এই প্রতিবিম্ব—", options: ["বাস্তৱ", "উলোটা", "কাল্পনিক আৰু উলোটা", "কাল্পনিক আৰু সোজা"], correctIndex: 3, explanation: "অবতল দৰ্পণৰ ধ্রুৱ আৰু ফোকাসৰ মাঝত বস্তু থ'লে দৰ্পণৰ পিছফালে কাল্পনিক, সোজা আৰু বিবৰ্ধিত প্রতিবিম্ব গঠন হয়।" },
  { question: "ফোকাস দূরত্ব f থোৱা উত্তল লেন্সৰ সহায়ত বাস্তৱ, উলোটা আৰু বস্তুতকৈ বৃহৎ প্রতিবিম্ব পাবৰ বাবে বস্তুটো ক'ত থ'ব লাগিব?", options: ["লেন্সৰ ফোকাসত", "লেন্সৰ 2f দূরত্বত", "লেন্সৰ f আৰু 2f ৰ মাঝত", "লেন্সৰ 2f আৰু অনন্তৰ মাঝত"], correctIndex: 2, explanation: "বস্তুটো উত্তল লেন্সৰ f আৰু 2f ৰ মাঝত থ'লে, বিপৰীত ফালে 2f তকৈ দূৰত বাস্তৱ, উলোটা আৰু বিবৰ্ধিত (বস্তুতকৈ বৃহৎ) প্রতিবিম্ব গঠন হয়।" },
  { question: "গোলকীয় দৰ্পণৰ বাবে ফোকাস দূরত্ব f আৰু বক্রতার ব্যাসাৰ্ধ R ৰ মাজৰ সম্পর্ক হ'ল—", options: ["f = 2R", "f = R/2", "f = R/4", "f = 2/R"], correctIndex: 1, explanation: "যিকোনো গোলকীয় দৰ্পণৰ বাবে f = R/2।" },
  { question: "তলৰ কোনটো মাধ্যমত আলোকৰ বেগ আটাইতকৈ বেছি হ'ব?", options: ["বাতাস", "পানী", "কাঁচ", "শূন্যস্থান (vacuum)"], correctIndex: 3, explanation: "আলোক শূন্যস্থানত আটাইতকৈ বেগেৰে, 3×10⁸ m/s বেগেৰে যাত্রা কৰে — ইয়াৰ সম্ভাৱ্য সর্বোচ্চ বেগ।" },
  { question: "এটা অবতল লেন্সৰ বক্রতার ব্যাসাৰ্ধ 20 cm। তাৰ ফোকাস দূরত্ব হ'ব—", options: ["-20 cm", "-10 cm", "40 cm", "10 cm"], correctIndex: 1, explanation: "f = R/2 = 20/2 = 10 cm মাত্রাত; ই অবতল (অপসারী) লেন্স হোৱাৰ বাবে f = −10 cm।" },
  { question: "গাড়ীত লগোৱা পিছফালৰ দৰ্পণে (rear view mirror) সৃষ্টি কৰা বিবৰ্ধন—", options: ["একতকৈ কম", "একতকৈ বেছি", "একৰ সমান", "বস্তুৰ স্থানৰ ওপরত নির্ভৰ কৰি (a) বা (b)"], correctIndex: 0, explanation: "পিছফালৰ দৰ্পণ এটা উত্তল দৰ্পণ, যিয়ে সদায় কাল্পনিক, সোজা, সংকুচিত প্রতিবিম্ব গঠন কৰে — সেয়েহে ইয়াৰ বিবৰ্ধন সদায় একতকৈ কম (m < 1)।" },
  { question: "কাল্পনিক প্রতিবিম্বৰ তলৰ ধর্মসমূহ বিবেচনা কৰক:\nA. পর্দাত প্রক্ষেপ কৰিব নোৱাৰি   B. অবতল আৰু উত্তল লেন্স দুয়োটাৰেই দ্বাৰা গঠিত হয়\nC. সদায় সোজা   D. সদায় উলোটা\nসঁচা ধর্মসমূহ হ'ল—", options: ["(A) আৰু (D)", "(A) আৰু (B)", "(A), (B) আৰু (C)", "(A), (B) আৰু (D)"], correctIndex: 2, explanation: "কাল্পনিক প্রতিবিম্ব সদায় সোজা হয়, পর্দাত প্রক্ষেপ কৰিব নোৱাৰি, আৰু অবতল ও উত্তল লেন্স দুয়োটাৰেই দ্বাৰা গঠিত হয়। সেয়েহে A, B আৰু C সঁচা; D ভুল কাৰণ কাল্পনিক প্রতিবিম্ব কেতিয়াও উলোটা নহয়।" },
  { question: "সূর্যৰপরা আহি ৰশ্মি অবতল দৰ্পণৰ সমুখত 15 cm দূরত্বত মিলিত হয়। বস্তুৰ প্রতিবিম্বৰ আকাৰ বস্তুটোৰ আকাৰৰ সমান হ'বৰ বাবে বস্তুটো ক'ত থ'ব লাগিব?", options: ["দৰ্পণৰ সমুখত 15 cm", "দৰ্পণৰ সমুখত 30 cm", "দৰ্পণৰ সমুখত 15 cm আৰু 30 cm ৰ মাঝত", "দৰ্পণৰ সমুখত 30 cm তকৈ বেছি"], correctIndex: 1, explanation: "সূর্যৰপরা আহি সমান্তরাল ৰশ্মি ফোকাসত মিলিত হয়, সেয়েহে f = 15 cm। সমান আকাৰৰ বাস্তৱ, উলোটা প্রতিবিম্ব কেৱল বস্তুটো বক্রতার কেন্দ্রত, অর্থাৎ 2f = 30 cm ত থ'লেহে গঠন হয়।" },
  { question: "তলৰ কোনটো সঁচা নহয়?", options: ["আলোক এক বৈদ্যুতচুম্বকীয় তৰংগ", "আলোক সৰল ৰেখাত যাত্রা কৰে", "আলোক এক transverse তৰংগ", "আলোক এক longitudinal তৰংগ"], correctIndex: 3, explanation: "আলোক এক বৈদ্যুতচুম্বকীয়, transverse তৰংগ যিয়ে সৰল ৰেখাত যাত্রা কৰে — ই longitudinal তৰংগ নহয়, সেয়েহে (d) ভুল।" },
  { question: "·········· লেন্সৰ বিবৰ্ধন সদায় 1 তকৈ কম।", options: ["অবতল", "উত্তল", "যিকোনো", "চিলিন্দ্রিকেল"], correctIndex: 0, explanation: "অবতল লেন্সে যিকোনো স্থানৰ বস্তুৰ বাবে সদায় সংকুচিত, কাল্পনিক, সোজা প্রতিবিম্ব গঠন কৰে, সেয়েহে ইয়াৰ বিবৰ্ধন সদায় 1 তকৈ কম।" },
  { question: "প্রতিফলন বা প্রতিসরণৰ পিছত আলোক ৰশ্মিয়ে বাস্তৱ প্রতিবিম্ব গঠন কৰে যেতিয়া—\nI. ৰশ্মিসমূহ সঁচাকৈ পৰস্পর মিলিত/অতিক্রম হয়।\nII. ৰশ্মিসমূহ সঁচাকৈ এক বিন্দুত অভিসারিত হয়।\nIII. পিছফালে প্রসারিত কৰিলে মিলিত হোৱা যেন লাগে।\nIV. এক বিন্দুৰপরা অপসারিত হোৱা যেন লাগে।\nতলৰ কোনটো বিবৃতি সঁচা?", options: ["(I) আৰু (IV)", "(II) আৰু (IV)", "(I) আৰু (II)", "(II) আৰু (III)"], correctIndex: 2, explanation: "বাস্তৱ প্রতিবিম্ব কেৱল তেতিয়া গঠন হয় যেতিয়া আলোক ৰশ্মি সঁচাকৈ পৰস্পর মিলিত/অতিক্রম হয় বা সঁচাকৈ এক বিন্দুত অভিসারিত হয় — I আৰু II দুয়োটাই বাস্তৱ প্রতিবিম্বৰ একেটা চর্তৰেই বিভিন্ন ৰূপ।" },
  { question: "ফোকাস দূরত্ব f থোৱা এটা অবতল লেন্সে বস্তুৰ n গুণ আকাৰৰ প্রতিবিম্ব গঠন কৰে। লেন্সৰপরা বস্তুৰ দূরত্ব হ'ল—", options: ["(1−n)f", "(1+n)f", "((1+n)/n)f", "((1−n)/n)f"], correctIndex: 3, explanation: "v = nu আৰু লেন্স সূত্র 1/v − 1/u = 1/f ব্যবহাৰ কৰি সমাধান কৰিলে u = ((1−n)/n) f পোৱা যায়।" },
  { question: "এজনী ছোৱালী জাদু দৰ্পণৰ সমুখত থিয় হৈ আছে। তাইৰ মূৰৰ প্রতিবিম্ব বৃহৎ, শৰীরৰ মধ্যভাগ একে আকাৰৰ আৰু ভৰিৰ ভাগ সৰু দেখা পায়। ওপৰৰপরা তললৈ জাদু দৰ্পণৰ সংযোজনৰ ক্রম হ'ল—", options: ["সমতল, উত্তল আৰু অবতল", "উত্তল, অবতল আৰু সমতল", "অবতল, সমতল আৰু উত্তল", "উত্তল, সমতল আৰু অবতল"], correctIndex: 2, explanation: "অবতল দৰ্পণ (বৃহৎ ফোকাস দূরত্বৰ) মূৰটো বিবৰ্ধিত কৰে, সমতল দৰ্পণ মধ্যভাগ একে আকাৰত ৰাখে, আৰু উত্তল দৰ্পণ ভৰিৰ ভাগ সংকুচিত কৰে — সেয়েহে ওপৰৰপরা তললৈ: অবতল, সমতল, উত্তল।" },
  { question: "যিকোনো দূরত্বতেই দৰ্পণে গঠন কৰা প্রতিবিম্ব সদায় সোজা হ'লে, দৰ্পণটো হ'ব—", options: ["কেৱল সমতল", "কেৱল অবতল", "কেৱল উত্তল", "সমতল বা উত্তল যিকোনো"], correctIndex: 3, explanation: "সমতল আৰু উত্তল দৰ্পণ যিকোনো বস্তু দূরত্বৰ বাবে সদায় সোজা প্রতিবিম্ব গঠন কৰে।" },
  { question: "সমতল দৰ্পণৰ ফোকাস দূরত্ব—", options: ["শূন্য", "অসীম", "25 cm", "-25 cm"], correctIndex: 1, explanation: "সমতল দৰ্পণক অসীম বক্রতার ব্যাসাৰ্ধৰ গোলকীয় দৰ্পণ বুলি ভাবিব পাৰি, সেয়েহে ইয়াৰ ফোকাস দূরত্ব অসীম।" },
  { question: "প্রতিফলনৰ নিয়মসমূহ কোনটোৰ বাবে প্রযোজ্য?", options: ["কেৱল সমতল দৰ্পণ", "কেৱল অবতল দৰ্পণ", "কেৱল উত্তল দৰ্পণ", "আকৃতি নির্বিশেষে সকলো দৰ্পণ"], correctIndex: 3, explanation: "প্রতিফলনৰ নিয়মসমূহ যিকোনো সমতল পৃষ্ঠৰপরা প্রতিফলিত আলোকৰ বাবে প্রযোজ্য, দৰ্পণৰ আকৃতি নির্বিশেষে।" },
  { question: "দুটা মাধ্যমৰ সীমা পৃষ্ঠৰ ওপরত স্বাভাৱিকভাৱে (normally) আপতিত হোৱা আলোক ৰশ্মিৰ প্রতিসরণ কোণ হ'ব—", options: ["শূন্য", "45°", "60°", "80°"], correctIndex: 0, explanation: "স্বাভাৱিক আপতনৰ ক্ষেত্রত (আপতন কোণ শূন্য, ৰশ্মি স্বাভাৱিকৰ মাজেৰে যায়), আপতন কোণ আৰু প্রতিসরণ কোণ দুয়োটাই শূন্য হয় — ৰশ্মি কোনো বঁকা নোহোৱাকৈ পোনে পোনে যায়।" },
  { question: "এটা গোলকীয় দৰ্পণ আৰু এটা পাতল গোলকীয় লেন্স দুয়োটাৰে ফোকাস দূরত্ব −15 cm। দৰ্পণ আৰু লেন্স হ'ব পাৰে—", options: ["দুয়োটাই অবতল", "দুয়োটাই উত্তল", "দৰ্পণ অবতল আৰু লেন্স উত্তল", "দৰ্পণ উত্তল আৰু লেন্স অবতল"], correctIndex: 0, explanation: "ঋণাত্মক ফোকাস দূরত্ব অবতল দৰ্পণ আৰু অবতল (অপসারী) লেন্স দুয়োটাৰে বাবে লোৱা হয় — সেয়েহে দুয়োটাই অবতল হ'ব লাগিব।" },
  { question: "এটা আলোক ৰশ্মি A মাধ্যমৰপরা B মাধ্যমলৈ যাওঁতে B ত সোমাওঁতে স্বাভাৱিকৰ ফালে বঁকা হয়। A ৰ প্রতি B ৰ প্রতিসরাংক হ'ব—", options: ["একতকৈ বেছি", "একতকৈ কম", "একৰ সমান", "শূন্য"], correctIndex: 0, explanation: "B ত সোমাওঁতে ৰশ্মি স্বাভাৱিকৰ ফালে বঁকা হোৱাৰ বাবে, B অধিক ঘন (optically denser) আৰু A তকৈ বেছি প্রতিসরাংক ও কম বেগৰ — সেয়েহে A ৰ প্রতি B ৰ প্রতিসরাংক একতকৈ বেছি।" },
  { question: "10 cm ফোকাস দূরত্বৰ অবতল দৰ্পণৰপরা 20 cm দূরত্বত বস্তু থ'লে, প্রতিবিম্ব গঠন হয় ……", options: ["দৰ্পণৰ পিছফালে", "দৰ্পণ আৰু ফোকাসৰ মাঝত", "ফোকাসত", "দৰ্পণৰ বক্রতার কেন্দ্রত"], correctIndex: 3, explanation: "f = −10 cm, u = −20 cm ব্যবহাৰ কৰি দৰ্পণ সূত্রত: 1/v = 1/f − 1/u = −1/10 + 1/20 = −1/20, সেয়েহে v = −20 cm — প্রতিবিম্ব দৰ্পণৰ বক্রতার কেন্দ্রত গঠন হয়।" },
  { question: "স্তম্ভ I (নিয়ম বা সূত্র) ক স্তম্ভ II (সূত্ৰ বা সম্পর্ক) ৰ সৈতে মিল কৰক:\nA. লেন্স সূত্ৰ  B. স্নেলৰ নিয়ম  C. প্রতিসরাংক  D. লেন্সৰ ক্ষমতা\n(i) ∠i = ∠r  (ii) 1/v − 1/u = 1/f  (iii) c/v  (iv) 1/f (মিটাৰত)", options: ["(i)(iii)(iv)(ii)", "(ii)(iv)(i)(iii)", "(ii)(i)(iii)(iv)", "(iii)(i)(iv)(ii)"], correctIndex: 2, explanation: "A→(ii) লেন্স সূত্র 1/v−1/u=1/f; B→(i) স্নেলৰ নিয়মৰ সম্পর্ক; C→(iii) প্রতিসরাংক = c/v; D→(iv) লেন্সৰ ক্ষমতা = 1/f (মিটাৰত)। সেয়েহে ক্রমটো হ'ল (ii)(i)(iii)(iv)।" },
  { question: "+10 cm ফোকাস দূরত্ব থোৱা দৰ্পণৰ প্রকৃতি অভিসারী (converging)।", options: ["সঁচা", "ভুল", "কব নোৱাৰি", "আংশিক সঁচা/ভুল"], correctIndex: 1, explanation: "ভুল — ধনাত্মক ফোকাস দূরত্ব উত্তল (অপসারী) দৰ্পণৰ বাবে হয়; অভিসারী (অবতল) দৰ্পণৰ ফোকাস দূরত্ব ঋণাত্মক হয়।" },
  { question: "দুটা সমান্তরাল আলোক ৰশ্মিপুঞ্জ এটা বন্ধ বাকচৰ দুটা ছিদ্ৰৰ মাজেৰে সোমাই বিপৰীত ফালৰ আনুটা দুটা ছিদ্ৰৰ মাজেৰে নিৰ্গত হয়, আৰু নিৰ্গত হওঁতে মূল ৰশ্মিপুঞ্জৰ সমান্তরালেই থাকে (কেৱল কিছু স্থানান্তরিত হয়)। বাকচৰ ভিতৰত তলৰ কোনটো থাকিব পাৰে?", options: ["এটা আয়তাকার কাঁচ স্লাব", "এটা উত্তল লেন্স", "এটা অবতল লেন্স", "এটা প্রিজম"], correctIndex: 0, explanation: "আয়তাকার কাঁচ স্লাবৰ দুটা সমান্তরাল পৃষ্ঠত ৰশ্মি সমান আৰু বিপৰীত পরিমাণে বঁকা হয়, সেয়েহে নিৰ্গত ৰশ্মি আপতিত ৰশ্মিৰ সমান্তরাল (কেৱল স্থানান্তরিত) থাকে — যিটো বাকচৰ আচরণৰ সৈতে সম্পূর্ণ মিল খায়।" },
  { question: "এটা সমতল দৰ্পণৰ সমুখত 10 cm দূরত্বত বস্তু থ'লে, দৰ্পণৰপরা প্রতিবিম্বৰ দূরত্ব হ'ব—", options: ["5 cm", "10 cm", "20 cm", "0"], correctIndex: 1, explanation: "সমতল দৰ্পণত, দৰ্পণৰ পিছফালে প্রতিবিম্বৰ দূরত্ব সদায় দৰ্পণৰ সমুখফালে বস্তুৰ দূরত্বৰ সমান হয় — সেয়েহে 10 cm।" },
  { question: "আলোক ৰশ্মি 90° কোণত মাধ্যমৰ সীমা পৃষ্ঠত আপতিত হ'লে কোনো প্রতিসরণ নঘটে।", options: ["সঁচা", "ভুল", "কব নোৱাৰি", "আংশিক সঁচা/ভুল"], correctIndex: 0, explanation: "সঁচা — স্বাভাৱিক আপতনত (আপতন কোণ 0°, অর্থাৎ ৰশ্মিটো পৃষ্ঠৰ সৈতে 90° কোণত থোৱা স্বাভাৱিকৰ মাজেৰে যায়), আপতন আৰু প্রতিসরণ কোণ দুয়োটাই 0° হয়, সেয়েহে ৰশ্মিটো কোনো বঁকা নোহোৱাকৈ পোনে পোনে যায়।" },
  { question: "স্তম্ভ I (বিবৰ্ধন, m) ক স্তম্ভ II (প্রতিবিম্বৰ প্রকৃতি) ৰ সৈতে মিল কৰক:\nA. m = 1  B. m < 1  C. m > 0  D. m < 0\n(i) উলোটা প্রতিবিম্ব  (ii) সংকুচিত প্রতিবিম্ব  (iii) সোজা প্রতিবিম্ব  (iv) প্রতিবিম্বৰ আকাৰ = বস্তুৰ আকাৰ", options: ["(iv)(ii)(iii)(i)", "(ii)(iv)(ii)(iii)", "(iv)(iii)(ii)(i)", "(i)(ii)(iii)(iv)"], correctIndex: 0, explanation: "A→(iv): m=1 ৰ অর্থ প্রতিবিম্বৰ আকাৰ বস্তুৰ আকাৰৰ সমান। B→(ii): m<1 ৰ অর্থ সংকুচিত প্রতিবিম্ব। C→(iii): m>0 ৰ অর্থ সোজা প্রতিবিম্ব। D→(i): m<0 ৰ অর্থ উলোটা প্রতিবিম্ব। সেয়েহে ক্রমটো (iv)(ii)(iii)(i)।" },
  { question: "এটা 10 mm দীঘল আলপিন অবতল দৰ্পণৰ সমুখত পোনাকৈ থোৱা হৈছে। আলপিনৰ 5 mm দীঘল প্রতিবিম্ব দৰ্পণৰ সমুখত 30 cm দূরত্বত গঠন হয়। এই দৰ্পণৰ ফোকাস দূরত্ব হ'ব—", options: ["-30 cm", "-20 cm", "-40 cm", "-60 cm"], correctIndex: 1, explanation: "h = 1 cm, h' = −0.5 cm (বাস্তৱ প্রতিবিম্ব), v = −30 cm। m = −v/u = h'/h ⟹ −(−30)/u = −0.5 ⟹ u = −60 cm। দৰ্পণ সূত্র ব্যবহাৰ কৰি: 1/f = 1/v + 1/u = 1/(−30) + 1/(−60) = −3/60 ⟹ f = −20 cm।" },
  { question: "অবতল দৰ্পণৰ সমুখত বস্তুটো ক'ত থ'লে তাৰ প্রতিবিম্ব সোজা আৰু বৃহৎ আকাৰৰ হ'ব?", options: ["দৰ্পণৰ বক্রতার কেন্দ্ৰত (C)", "দৰ্পণৰ ফোকাস বিন্দুত (f)", "বক্রতার কেন্দ্ৰ (C) আৰু ফোকাস বিন্দু (f) ৰ মাঝত", "ধ্রুৱ (P) আৰু ফোকাস বিন্দু (f) ৰ মাঝত"], correctIndex: 3, explanation: "অবতল দৰ্পণৰ ধ্রুৱ (P) আৰু ফোকাস (f) ৰ মাঝতহে বস্তু থ'লে প্রতিবিম্ব কাল্পনিক, সোজা আৰু বিবৰ্ধিত (বৃহৎ আকাৰৰ) হয়।" },
  { question: "f ফোকাস দূরত্বৰ উত্তল দৰ্পণে বস্তুৰ 1/n অংশ আকাৰৰ প্রতিবিম্ব গঠন কৰে। দৰ্পণৰপরা বস্তুৰ দূরত্ব হ'ল ……", options: ["((n+1)/n)f", "(n+1)f", "(n−1)f", "((n−1)/n)f"], correctIndex: 1, explanation: "m = 1/n = −v/(−u) ⟹ v = u/n; দৰ্পণ সূত্ৰ 1/v + 1/u = 1/f ব্যবহাৰ কৰিলে n/u + 1/u = 1/f পোৱা যায়, সেয়েহে u = (n+1)f।" },
  { question: "দূৰৱর্তী বস্তুৰ প্রতিবিম্ব গঠন কৰি অবতল দৰ্পণৰ ফোকাস দূরত্ব নিৰ্ণয় কৰিবৰ বাবে পর্দাটো ক'ত থ'ব লাগিব?", options: ["যিকোনো দিশত", "45° কোণত হেলনীয়াভাৱে", "দৰ্পণৰ তলৰ সৈতে সমকোণে", "দৰ্পণৰ তলৰ সমান্তরালে"], correctIndex: 3, explanation: "অবতল দৰ্পণে গঠন কৰা প্রতিবিম্ব সদায় মূখ্য অক্ষৰ সৈতে সমকোণী হয়, সেয়েহে পর্দাটো স্পষ্টভাৱে ধরিবৰ বাবে দৰ্পণৰ তলৰ সমান্তরালে থ'ব লাগিব।" },
  { question: "ঘন মাধ্যমৰপরা হাল্কা মাধ্যমলৈ আলোক ৰশ্মি গ'লে, প্রতিসরণ কোণ আপতন কোণতকৈ কম হ'ব।", options: ["সঁচা", "ভুল", "কব নোৱাৰি", "আংশিক সঁচা/ভুল"], correctIndex: 1, explanation: "ভুল — ঘনৰপরা হাল্কা মাধ্যমলৈ গ'লে ৰশ্মি স্বাভাৱিকৰপরা দূরৈত বঁকা হয়, সেয়েহে প্রতিসরণ কোণ আপতন কোণতকৈ বেছিয়েই হয়, কম নহয়।" },
  { question: "প্রতিজ্ঞা (A): এটা বিন্দু বস্তু স্থিৰ ৰাখি, সমতল দৰ্পণটো লৰচৰ কৰিলে প্রতিবিম্বও লৰচৰ কৰিব।\nযুক্তি (R): সমতল দৰ্পণৰ ক্ষেত্রত, যিকোনো বিন্দুৰপরা বস্তু আৰু তাৰ প্রতিবিম্বৰ দূরত্ব সমান।", options: AR_OPTIONS_AS, correctIndex: 0, explanation: "সমতল দৰ্পণৰ প্রতিবিম্ব সদায় বস্তুটো সমুখফালে যিমান দূৰত থাকে, দৰ্পণৰ পিছফালে সিমানেই দূৰত থাকে। দৰ্পণ লৰচৰ কৰিলে বস্তু স্থিৰ থাকিলেও এই সমান-দূরত্বৰ সম্পর্কৰ বাবে প্রতিবিম্বও লৰচৰ কৰিবলগীয়া হয় — সেয়েহে R এ A ৰ সঠিক ব্যাখ্যা দিয়ে।" },
  { question: "প্রতিজ্ঞা (A): অভিসারী লেন্সৰ ধর্ম সকলো মাধ্যমত একে নাথাকে।\nযুক্তি (R): লেন্সৰ ধর্ম — অপসারী নে অভিসারী — চাৰিওফালৰ মাধ্যমৰ ওপরত নির্ভর নকরে।", options: AR_OPTIONS_AS, correctIndex: 2, explanation: "লেন্সৰ ধর্ম চাৰিওফালৰ মাধ্যমৰ প্রতিসরাংকৰ ওপরত নির্ভর কৰে। সেয়েহে A সঁচা (অভিসারী ধর্ম মাধ্যমৰ সৈতে সলনি হয়) কিন্তু R ভুল (কাৰণ লেন্সৰ আচরণ আসলতে মাধ্যমৰ ওপরত নির্ভর কৰে, R ৰ স্বাধীনতার দাবী ভুল)।" },
  { question: "প্রতিজ্ঞা (A): পানীৰ তলত অবতল দৰ্পণ থ'লে তাৰ ফোকাস দূরত্ব বাঢ়িব।\nযুক্তি (R): অবতল দৰ্পণৰ ফোকাস দূরত্ব যি মাধ্যমত থোৱা হয় তাৰ ওপরত নির্ভর নকরে।", options: AR_OPTIONS_AS, correctIndex: 3, explanation: "ফোকাস দূরত্ব দৰ্পণৰ নিজৰ ধর্ম, যিকোনো মাধ্যমৰ ওপরত নির্ভর নকরে — সেয়েহে অবতল দৰ্পণ পানীৰ তলত থ'লেও তাৰ ফোকাস দূরত্ব একেই থাকে, বাঢ়ি নাযায়। সেয়েহে A ভুল আৰু R সঁচা।" },
  { question: "প্রতিজ্ঞা (A): দুটা পৃথক বস্তুৰে গঠিত এটা উত্তল লেন্সৰ মূখ্য অক্ষত এটা বিন্দু বস্তু থ'লে, লেন্সে দুটা প্রতিবিম্ব গঠন কৰিব।\nযুক্তি (R): উত্তল লেন্সে গঠন কৰা প্রতিবিম্ব সদায় কাল্পনিক হয়।", options: AR_OPTIONS_AS, correctIndex: 2, explanation: "লেন্সটো দুটা বস্তুৰে গঠিত হোৱাৰ বাবে তাৰ দুটা প্রতিসরাংক আৰু দুটা ফোকাস দূরত্ব থাকে, ফলত দুটা প্রতিবিম্ব গঠন হয় — সেয়েহে A সঁচা। কিন্তু উত্তল লেন্সে গঠন কৰা প্রতিবিম্ব সাধারণতে বাস্তৱ হয় (কেৱল বস্তু ফোকাস আৰু আলোক কেন্দ্রৰ মাঝত থ'লেহে কাল্পনিক হয়), সেয়েহে R ভুল।" },
  { question: "প্রতিজ্ঞা (A): গগলসৰ লেন্সৰ পৃষ্ঠ বঁকা হ'লেও ইয়াৰ কোনো ক্ষমতা নাথাকে।\nযুক্তি (R): গগলসৰ ক্ষেত্রত, দুয়োটা বঁকা পৃষ্ঠৰ বক্রতার ব্যাসাৰ্ধ সমান।", options: AR_OPTIONS_AS, correctIndex: 0, explanation: "গগলসৰ দুয়োটা বঁকা পৃষ্ঠৰ বক্রতার ব্যাসাৰ্ধ সমান হোৱাৰ বাবে ফোকাস দূরত্ব অসীম হয়, ফলত ক্ষমতা P=1/f=0। সেয়েহে A সঁচা, R সঁচা, আৰু R এ A ৰ সঠিক ব্যাখ্যা দিয়ে।" },
  { question: "তলত দিয়া কথাখিনি পঢ়ি উত্তৰ দিয়ক: আলোক হ'ল শক্তিৰ এক ৰূপ যিয়ে আমাৰ চক্ষুত দৃষ্টিৰ অনুভূতি সৃষ্টি কৰে; সমতল পৃষ্ঠত পৰি আলোক ৰশ্মি ওলটি অহাকে প্রতিফলন বোলে। গাড়ীৰ চালকৰ ফালৰ বাহিরৰ দৰ্পণত সাধারণতে এটা গোলকীয় দৰ্পণ ব্যবহাৰ কৰা হয়, যাৰ ওপরত লিখা থাকে 'এই দৰ্পণত গাড়ী দেখাতকৈ ওচৰত থাকে।' গাড়ীৰ চালকৰ ফালৰ বাহিরৰ দৰ্পণত সাধারণতে কি প্রকাৰৰ দৰ্পণ ব্যবহাৰ কৰা হয়?", options: ["সমতল দৰ্পণ", "অবতল দৰ্পণ", "উত্তল দৰ্পণ", "জাদু দৰ্পণ"], correctIndex: 2, explanation: "গাড়ীৰ চালকৰ ফালৰ দৰ্পণত উত্তল দৰ্পণ ব্যবহাৰ কৰা হয়, কাৰণ ই সদায় সোজা প্রতিবিম্ব দিয়ে আৰু ইয়াৰ দৃষ্টি ক্ষেত্র বহল, যিয়ে চালকক পিছফালৰ বাটৰ অধিক ভাগ দেখাত সহায় কৰে।" },
  { question: "(ওপৰৰ একেটা প্রসংগ) দৰ্পণৰপরা যিমানেই দূরত থাকিলেও, তোমাৰ প্রতিবিম্ব সদায় সোজা দেখা গ'লে, দৰ্পণটো হ'ব পাৰে—", options: ["সমতল", "অবতল", "উত্তল", "সমতল বা উত্তল যিকোনো"], correctIndex: 3, explanation: "সমতল আৰু উত্তল দৰ্পণ দুয়োটাইয়ে যিকোনো দূরত্বৰ বস্তুৰ বাবে সদায় সোজা প্রতিবিম্ব গঠন কৰে, সেয়েহে দৰ্পণটো সমতল বা উত্তল যিকোনো হ'ব পাৰে।" },
  { question: "(ওপৰৰ একেটা প্রসংগ) 60 cm বক্রতার ব্যাসাৰ্ধৰ উত্তল দৰ্পণৰপরা 10 cm দূরত্বত বস্তু থ'লে, প্রতিবিম্বৰ স্থান নির্ণয় কৰক।", options: ["4 cm", "7.5 cm", "10 cm", "12.5 cm"], correctIndex: 1, explanation: "f = R/2 = 30 cm (ধনাত্মক, উত্তল দৰ্পণ)। u = −10 cm। দৰ্পণ সূত্র 1/v = 1/f − 1/u = 1/30 − (−1/10) = 1/30 + 1/10 = 4/30 ⟹ v = 7.5 cm।" },
  { question: "(ওপৰৰ একেটা প্রসংগ) দৰ্পণৰ ফোকাস দূরত্ব 12 cm। বক্রতার ব্যাসাৰ্ধ হ'ব—", options: ["12 cm", "24 cm", "20 cm", "36 cm"], correctIndex: 1, explanation: "বক্রতার ব্যাসাৰ্ধ R = 2f = 2 × 12 = 24 cm।" },
  { question: "তলত দিয়া কথাখিনি পঢ়ি উত্তৰ দিয়ক: শূন্যস্থানৰ প্রতি কোনো মাধ্যমৰ প্রতিসরাংককে পরম প্রতিসরাংক বোলে, μ = sin i / sin r। পরম প্রতিসরাংক আলোকৰ বেগৰ সৈতে কেনেদৰে সম্পর্কিত?", options: ["μ = c/v_m", "μ = c·v_m", "μ_c = V_m", "vμ = c"], correctIndex: 0, explanation: "পরম প্রতিসরাংক μ = (শূন্যস্থানত আলোকৰ বেগ, c) / (সেই মাধ্যমত আলোকৰ বেগ, v_m), অর্থাৎ μ = c/v_m।" },
  { question: "(ওপৰৰ একেটা প্রসংগ) A, B, C আৰু D মাধ্যমৰ পরম প্রতিসরাংক ক্রমে 1.54, 1.33, 2.42 আৰু 1.65। এই মাধ্যমসমূহৰ মাজত কোনটোত আলোক আটাইতকৈ বেগেৰে যাত্রা কৰে?", options: ["A", "B", "C", "D"], correctIndex: 1, explanation: "B ৰ প্রতিসরাংক আটাইতকৈ কম (1.33), অর্থাৎ ই আটাইতকৈ কম ঘন (optically rarer), সেয়েহে আলোক B মাধ্যমত আটাইতকৈ বেগেৰে যাত্রা কৰে।" },
  { question: "(ওপৰৰ একেটা প্রসংগ) বাতাসত আলোকৰ বেগ 3×10⁸ ms⁻¹ আৰু A মাধ্যমত 2.5×10⁸ ms⁻¹। A ৰ প্রতিসরাংক হ'ব—", options: ["1.2", "0.5", "4.5", "1.5"], correctIndex: 0, explanation: "A ৰ প্রতিসরাংক = বাতাসত আলোকৰ বেগ / A মাধ্যমত আলোকৰ বেগ = (3×10⁸)/(2.5×10⁸) = 1.2।" },
];

function buildSets(questions: Omit<McqInput, "setNumber" | "order">[], startSet: number): McqInput[] {
  const out: McqInput[] = [];
  questions.forEach((q, i) => {
    const setNumber = startSet + Math.floor(i / 10);
    const order = (i % 10) + 1;
    out.push({ ...q, setNumber, order });
  });
  return out;
}

async function run() {
  if (englishQuestions.length !== 60 || assameseQuestions.length !== 60) {
    throw new Error(`Expected 60+60 questions, got ${englishQuestions.length}+${assameseQuestions.length}`);
  }

  const all = [...buildSets(englishQuestions, 1), ...buildSets(assameseQuestions, 7)];

  const col = db.collection("mcqs");
  let batch = db.batch();
  let count = 0;

  for (const mcq of all) {
    const ref = col.doc();
    batch.set(ref, {
      chapterId: CHAPTER_ID,
      question: mcq.question,
      options: mcq.options,
      correctIndex: mcq.correctIndex,
      explanation: mcq.explanation,
      order: mcq.order,
      setNumber: mcq.setNumber,
      createdAt: new Date(),
    });
    count++;
    if (count % 400 === 0) {
      await batch.commit();
      batch = db.batch();
      console.log(`  ...committed ${count}`);
    }
  }
  await batch.commit();

  console.log(`✓ Seeded ${count} MCQs into chapter "${CHAPTER_ID}"`);
  console.log(`  English sets: 1-6 (60 questions)`);
  console.log(`  Assamese sets: 7-12 (60 questions)`);
}

run().catch((err) => {
  console.error("✗ Seed failed:", err);
  process.exitCode = 1;
});
